config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'leagues#index'

  resources :leagues, except: [:edit] do
    resources :teams, except: %i[edit index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  self.implicit_order_column = :created_at
end

app/models/concerns/league_state_machine.rb
module LeagueStateMachine
  extend ActiveSupport::Concern

  # rubocop:disable Metrics/BlockLength
  included do
    include AASM

    aasm column: 'aasm_state' do
      state :pre_draft, initial: true
      state :drafting
      state :post_draft

      event :draft_started do
        transitions from: :pre_draft, to: :drafting
      end

      event :draft_completed do
        transitions from: :drafting, to: :post_draft
      end
    end
  end
end
# rubocop:enable Metrics/BlockLength

app/models/league.rb
class League < ApplicationRecord
  include LeagueStateMachine

  validates :name, presence: true, uniqueness: true
  has_many :rider_team_leagues, dependent: :destroy
  has_many :teams, dependent: :destroy
  has_many :riders, through: :rider_team_leagues
  belongs_to :user

  TEAM_SIZE = 9

  def pre_draft?
    aasm_state.eql? 'pre_draft'
  end

  def start_draft!
    randomize_draft_positions
    draft_started!
  end

  def available_riders
    Rider.all - riders
  end

  def update_draft_position
    draft_completed! and return if draft_complete?
    move_forward and return if draft_forward?

    move_backward
  end

  def draft_forward?
    draft_forward
  end

  def draft_complete?
    teams.find_by(draft_position: teams.size).riders.count == TEAM_SIZE
  end

  private

  def randomize_draft_positions
    teams.shuffle.each_with_index do |team, index|
      team.draft_position = index + 1
      team.save!
    end
  end

  def move_forward
    current_draft_position == teams.size ? reverse_direction : self.current_draft_position += 1
    save!
  end

  def move_backward
    current_draft_position == 1 ? reverse_direction : self.current_draft_position -= 1
    save!
  end

  def reverse_direction
    self.draft_forward = false if current_draft_position == teams.size

    self.draft_forward = true if current_draft_position == 1
  end
end

app/models/rider.rb
class Rider < ApplicationRecord
  has_many :rider_team_leagues, dependent: :destroy
  has_many :leagues, through: :rider_team_leagues
  has_many :teams, through: :rider_team_leagues
end

app/models/rider_team_league.rb
class RiderTeamLeague < ApplicationRecord
  belongs_to :rider
  belongs_to :league
  belongs_to :team
end

app/models/team.rb
class Team < ApplicationRecord
  validates :name, presence: true, uniqueness: { scope: :league_id, message: 'has already been taken in this league' }
  validates :draft_position, uniqueness: { scope: :league_id, allow_blank: true, message: 'has already been taken in this league' }
  belongs_to :league
  belongs_to :user
  has_many :rider_team_leagues, dependent: :destroy
  has_many :riders, through: :rider_team_leagues
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :username, presence: true,
                       uniqueness: {
                         case_sensitive: false
                       }

  has_many :leagues, dependent: :destroy
  has_many :teams, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[username email])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:username])
  end
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  before_action :authenticate_user!

  def index
    @leagues = League.order(:name)
  end

  def new
    @league = League.new
  end

  def create
    @league = League.new(league_params)
    if @league.save
      redirect_to leagues_path
    else
      render :new
    end
  end

  def show
    league
  end

  def destroy
    league.destroy
    redirect_to leagues_path
  end

  def update
    league.start_draft!
    render :show
  end

  private

  def league_params
    params.require(:league).permit(:name).merge(user_id: current_user.id)
  end

  def league
    @league ||= League.find(params[:id])
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :authenticate_user!

  def new
    @team = league.teams.build
  end

  def create
    @team = league.teams.build(team_params)
    if @team.save
      redirect_to league_path(league)
    else
      render :new
    end
  end

  def show
    team
  end

  def destroy
    team.destroy
    redirect_to league_path(league)
  end

  def update
    RiderTeamLeague.new(rider_id: params[:rider_id], team_id: team.id, league_id: league.id).save!
    league.update_draft_position
    team
    render :show
  end

  private

  def team_params
    params.require(:team).permit(:name, :rider_id).merge(user_id: current_user.id)
  end

  def league
    @league ||= League.find(params[:league_id])
  end

  def team
    @team ||= Team.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DraftACyclingTeam</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= button_to "logout", destroy_user_session_path, method: :delete  %>
    <%= yield %>
  </body>
</html>

app/views/leagues/_draft.html.haml
%h2= t '.draft_results'

- team = league.teams.where(draft_position: league.current_draft_position).first
%h3= t('.drafting_now', team: team.name, user: team.user.username)

%table{ border: 0, id: 'draft-results' }
  %thead
    %tr
      %th #
      %th Drafted by
      %th Country
      %th Team
      %th Rider
      %th Price
      %th Previous score
  %tbody
    - league.rider_team_leagues.each_with_index do |record, index|
      %tr
        %th= index + 1
        %th= record.team.name
        %td= record.rider.country
        %td= record.rider.team
        %td= record.rider.name
        %td= record.rider.price.to_i
        %td= record.rider.previous_score.to_i

app/views/leagues/index.html.haml
%html
  %head
  %body
    %h1= t '.title'
    - @leagues&.each do |league|
      %p= link_to(league.name, league_path(league.id))

    = link_to t('.create'),
        :new_league,
        type: 'submit',
        class: 'btn btn-primary'

app/views/leagues/new.html.haml
%html
  %head
  %body
    %h1= t '.title'
    = form_with model: @league do |form|
      - if @league.errors
        %p
          = @league.errors.full_messages.first.to_s

      %div
        = form.label :name
        = form.text_field :name, required: true

      %p
        = form.submit

      = link_to t('generic.back'), :leagues

app/views/leagues/show.html.haml
%html
  %head
  %body
    %h1= @league.name

    - if @league.pre_draft?
      %p Waiting for draft to start
    - if @league.drafting?
      = render 'draft', league: @league

    - @league&.teams&.each do |team|
      %p= link_to(team.name, league_team_path(@league.id, team.id))

    - if policy(@league).create_team?
      = link_to t('.create'), new_league_team_path(@league)

    - if policy(@league).destroy?
      = link_to t('.delete'),
          league_path(@league),
          method: :delete,
          data: { confirm: 'Are you sure?' }

    - if policy(@league).update?
      = link_to t('.start'),
          league_path(@league),
          method: :patch,
          data: { confirm: 'Are you sure?' }

    = link_to t('generic.back'), :leagues